# Site settings
title: Linux on PDAs project
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
        Linux on PDAs documentation, statuses and updates.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://linuxpda.github.io

# collections
collections:
        devices:
                output: true

# Build settings
markdown: kramdown
# defaults
safe: true
lsi: false
highlighter: pygments
